services:
  - type: worker
    name: skynixiq-weatherbot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
